### ISSUE TITLE
建议：设置里的表格高度和嵌入链接的<sheet-height>改为行数<rows>

### ISSUE THREAD

**Issue by Linzeal** [ljcoder2015/obsidian-excel#13]
建议：
1.3.3版本的设置里的默认表格高度，单位应该是像素px吧。因为本插件的嵌入体是表格，每行高度确定，建议设置里的表格高度和嵌入链接的`<sheet-height>`改为行数`<rows>`。

_Originally posted by @Linzeal in https://github.com/ljcoder2015/obsidian-excel/issues/7#issuecomment-1734713280_

**Comment by ljcoder2015** [comment]
高度灵活点，可能表格行数很多，末位显示半行，提现后面还可以滚动查看更多数据
