### ISSUE TITLE
[BUG] 区域单元格引用时函数结果错误

### ISSUE THREAD

**Issue by Linzeal** [ljcoder2015/obsidian-excel#14]
区域单元格引用时函数出错。
如下图，末行是各列前三行的SUM()，区域单元格引用时的结果是错误的。

测试环境：Obsidian v1.4.13沙箱仅有插件obsidian-excel v1.3.3。

![image](https://github.com/ljcoder2015/obsidian-excel/assets/20738431/9ccb4ff9-5885-45f5-ba99-1bb341f442dc)

**Comment by ljcoder2015** [comment]
fix 1.3.7
