### ISSUE TITLE
[BUG] 区域单元格包含首行时点“copy embed link”无法取得链接，不选首行则可取得链接。

### ISSUE THREAD

**Issue by Linzeal** [ljcoder2015/obsidian-excel#15]
如下图，选中B1:D5，点“copy embed link”无法取得链接，提示“Copy embed link failed”。不选首行则可取得链接。

测试环境：Obsidian v1.4.13沙箱仅有插件obsidian-excel v1.3.3。

![image](https://github.com/ljcoder2015/obsidian-excel/assets/20738431/f0b15896-f228-46a1-91a9-372ee673fa86)

**Comment by laphylee** [comment]
+1. 我也遇到了这个问题。

**Comment by ljcoder2015** [comment]
1.3.4 fix
