### ISSUE TITLE
It just doesn't work

### ISSUE THREAD

**Issue by avraam-inside** [ljcoder2015/obsidian-excel#18]
I either see this
![image](https://github.com/ljcoder2015/obsidian-excel/assets/52919010/dbf35f32-be68-4bf3-b14f-961dc11bd607)

Either that
![image](https://github.com/ljcoder2015/obsidian-excel/assets/52919010/8cdda9ab-72e8-480a-9620-71c37e52115e)

The "import" button doesn't race any reaction... 
I use the latest version of Obsidian 1.4.14

P.S. The plugin offers a very powerful toolkit, BUT!! HIEROGLYPHS IN DOCUMENTATION/PARAMETERS/COMMITS/ISSUES ARE TERRIBLE

I'm not even close to British myself, but hieroglyphs cause a "RUN" reaction... but very cool plugin...

**Comment by ljcoder2015** [comment]
1. Use Obsidian Sandbox  to install only this one plugin, Whether there are other plug-ins affected
2. The next version will be in multiple languages

**Comment by ljcoder2015** [comment]
1.3.4 fix
