### ISSUE TITLE
表格的copy html功能，只能拷贝一个单元格

### ISSUE THREAD

**Issue by zhoulonghao520** [ljcoder2015/obsidian-excel#19]
<img width="1159" alt="image" src="https://github.com/ljcoder2015/obsidian-excel/assets/144794808/94a3b62b-6418-4ff9-a065-4f47df612e86">

<img width="767" alt="image" src="https://github.com/ljcoder2015/obsidian-excel/assets/144794808/01077036-a409-4442-817e-bd508e5b27ef">

选中了N个单元格时，拷贝出来的内容如图二······

**Comment by ljcoder2015** [comment]
1.3.4 fix
