### ISSUE TITLE
如果这个插件嵌入后 能支持 obsidian-webpage-export 插件就完美了····

### ISSUE THREAD

**Issue by zhoulonghao520** [ljcoder2015/obsidian-excel#20]
https://github.com/KosmosisDire/obsidian-webpage-export

现在只能在obsidian 中有效，导出HTML是无效的···

![image](https://github.com/ljcoder2015/obsidian-excel/assets/144794808/8d84ce0c-f2f4-4728-87b0-e3b1cd4478ee)

<img width="1596" alt="image" src="https://github.com/ljcoder2015/obsidian-excel/assets/144794808/7c277253-11e0-4daa-894d-b8ef03efe2e0">

主要用obsidian写软件需求文档，所以文档都会导出html 供开发人员阅读，如果能支持导出html也正常显示 那obsidian真的就实现了only one了 对于我来说·····

**Comment by ljcoder2015** [comment]
这个应该是导出的HTML没引入 obsidian-excel 所需要的库，这个需要 obsidian-webpage-export 那边支持

**Comment by zhoulonghao520** [comment]
谢谢，我反馈给那位大佬了。

**Comment by ljcoder2015** [comment]
#33 可以用此方法实现
