### ISSUE TITLE
Renaming page tabs

### ISSUE THREAD

**Issue by aubreyz** [ljcoder2015/obsidian-excel#22]
This looks like it is developing into a great plugin. 

I found it impossible to edit the names of page tabs within a sheet - and if I did that they were prefixed with whatever was there before

**Comment by ljcoder2015** [comment]
What is the page tabs?
If you are referring to the bottom sheet name, double-click to modify it

**Comment by aubreyz** [comment]
Yes those tabs. When I double click them it does open an EMPTY data entry box. But then whatever you enter is added to whatever was there before. There is no way to delete the old content - so the tab becomes called sheet1mynewname and so on

**Comment by ljcoder2015** [comment]
I can delete the old content, I use delete key.
![rename](https://github.com/ljcoder2015/obsidian-excel/assets/15226918/a16a548e-9316-4928-9d65-482afc933845)

**Comment by aubreyz** [comment]
Apologies for the delay. That is not what happens this end. Here I am creating a new tag, then double clicking on the tab to rename, typing some random text and pressing enter. 
![Obsidian_gG2fyXN9O6](https://github.com/ljcoder2015/obsidian-excel/assets/25100168/1e79733a-b820-4d38-a57d-574c96d73c59)

**Comment by aubreyz** [comment]
i.e. when I double click on a tab I don't see a text entry box prefilled with the existing name, I see a blank entry box.
