### ISSUE TITLE
Problems on android

### ISSUE THREAD

**Issue by DrunkScienceMan** [ljcoder2015/obsidian-excel#23]
When clicking on a cell if you type into your keyboard nothing happens in the cell. No text appears.

If you swipe up/down/left/right you scroll in the sheet but the obsidian gestures themselves still show Up.

**Comment by ljcoder2015** [comment]
fix 1.3.5

**Comment by AdSecIT** [comment]
Issue still occurring, version 1.3.8 on Android Samsung S22

**Comment by ljcoder2015** [comment]
> Issue still occurring, version 1.3.8 on Android Samsung S22

It is OK in iOS，You can try double clicking and typing
