### ISSUE TITLE
打开后一片空白

### ISSUE THREAD

**Issue by ribber** [ljcoder2015/obsidian-excel#26]
![image](https://github.com/ljcoder2015/obsidian-excel/assets/5986011/5d4de265-a9f3-41f5-8153-22e6dfd9f827)

![image](https://github.com/ljcoder2015/obsidian-excel/assets/5986011/ef9fd4e7-55b4-4623-90c7-3d05b6edbf54)

好像把这个传给 Json parse 了，传的不是 json 格式

**Comment by ljcoder2015** [comment]
你创建的文件格式不正确，正常创建完是这样的，看看是不是有其它插件影响了文件的创建
```
---

excel-plugin: parsed

---


# Excel
[{"name":"sheet2","freeze":"A1","styles":[],"merges":[],"rows":{"5":{"cells":{"2":{"text":"sss"}}},"9":{"cells":{"3":{"text":"ddd"}}},"len":100},"cols":{"len":26},"validations":[],"autofilter":{}}]
```
这个内容没错，`getExcelData`会解析上面的内容

**Comment by ribber** [comment]
Thank you，经排查发现与 Filename Heading Sync 插件冲突，这个插件把 # 后面的内容改成了文件名
