### ISSUE TITLE
不支持pandoc

### ISSUE THREAD

**Issue by Juan-hwt** [ljcoder2015/obsidian-excel#29]
插件可以用，也能引用显示，但是pandoc导出的时候，有乱码……

**Comment by ljcoder2015** [comment]
#33 可以用此方法实现

**Comment by Juan-hwt** [comment]
![image](https://github.com/ljcoder2015/obsidian-excel/assets/82884966/034a0520-8678-4dcf-bf07-d1abb452bb93)
大神，能否设置一下，不显示这个链接，否则pandoc导出的时候，word里表格很多，导出一次，删除一次，我20几个文件，删半天……

**Comment by Juan-hwt** [comment]
![image](https://github.com/ljcoder2015/obsidian-excel/assets/82884966/ec607ffb-9700-45ad-b821-043a99b1d72e)
shibush是不是path设置有什么要求？？

**Comment by ljcoder2015** [comment]
@Juan-hwt 
```
![[file-folder/file-name#sheet-name|sri-sci:eri-eci<sheet-height>{html}]]
```
看下是否符合这个规则

**Comment by Juan-hwt** [comment]
> @Juan-hwt
> 
> ```
> ![[file-folder/file-name#sheet-name|sri-sci:eri-eci<sheet-height>{html}]]
> ```
> 
> 看下是否符合这个规则

按照插件导出，然后阅读模式下能显示，ctrl+shift+i下面继续报错，还是上面的错

![[Excel 2024-02-17 20.52.56.sheet#Sheet1|0-0:24-4<300>{html}]]

难道是要写![[2.xlsx#Sheet1|0-0:24-4<300>{html}]]？？

**Comment by ljcoder2015** [comment]
导出pdf没问题，导出Word 可能不行
[这篇文章](https://forum-zh.obsidian.md/t/topic/1930) 中看导出图片要设置命令，你可以试试你有没有用

**Comment by Juan-hwt** [comment]
图片我都设置好了，可以顺利导出图片的，

就是内嵌链接不行，能显示但是不能导出word。以前用您插件转化成html代码，倒是能导出，但是excel变了就非常麻烦

刚需是，打开文件或刷新时，能够自动读取/刷新excel，然后支持pandoc导出

感觉难点在于，合并单元格

谢谢大神！

**Comment by Juan-hwt** [comment]
刚测试过了，我也能成功导出html版本的pdf

**Comment by Juan-hwt** [comment]
貌似markdown只支持csv，而且csv能用pandoc导出，但是合并单元格先天不可以……
