### ISSUE TITLE
Embed link does not work - shows empty sheet

### ISSUE THREAD

**Issue by mikejlaurie** [ljcoder2015/obsidian-excel#31]
Creating an embed link and using it displays an empty image instead of a spreadsheet with content.

**Comment by ljcoder2015** [comment]
what is your embed link that I guess is incorrectly formatted

**Comment by mikejlaurie** [comment]
1. I create a sheet with values.
2. I created an embed link using the adding
3. I pasted the embed link into another note in obsidian.
4. The other note displayed a sheet, however no value that were captured in
the sheet in step 1 were displayed, all cells were empty.
