### ISSUE TITLE
能否实现，嵌入时显示HTML的设置

### ISSUE THREAD

**Issue by zhoulonghao520** [ljcoder2015/obsidian-excel#33]
![image](https://github.com/ljcoder2015/obsidian-excel/assets/144794808/09bec466-901b-40a4-90b1-29abcb9a907a)

目前嵌入时，是在嵌入界面能完整查看表格，但是 webpage to html  导出HTML无法正常查看。

我在大部分时候，文档是要导出html供其他人查看。因此 能否支持  以 html  嵌入方式？

这样，在文档中的很多合并行的复杂表格，我就可以借助这个EXCEL插件去编辑了。

虽然现在点击右上角，转HTML再贴过去需要的页面，也能实现。但是当表格多了，操作和管理起来就非常麻烦。

**Comment by zhoulonghao520** [comment]
![image](https://github.com/ljcoder2015/obsidian-excel/assets/144794808/90aaced6-e187-4214-8985-6429a5fc8c70)
j

![image](https://github.com/ljcoder2015/obsidian-excel/assets/144794808/8f209177-c375-4e76-a5d0-692eea2ef9ef)

就好像这样，这样就会很方便了。我用文件夹可以把文档中的表格全部管理的很好····

**Comment by ljcoder2015** [comment]
1.3.13 实现
