### ISSUE TITLE
转换成html时有BUG，右侧多出了很多列

### ISSUE THREAD

**Issue by zhoulonghao520** [ljcoder2015/obsidian-excel#34]
![image](https://github.com/ljcoder2015/obsidian-excel/assets/144794808/fdb3f7df-2052-4870-946d-73597257880b)

![image](https://github.com/ljcoder2015/obsidian-excel/assets/144794808/3febab36-6831-4004-8156-e81e06a9a953)

![image](https://github.com/ljcoder2015/obsidian-excel/assets/144794808/82e3d73a-6cb6-42e1-ac5b-c1f068d0128d)

转换成html时有BUG，右侧多出了很多列

**Comment by zhoulonghao520** [comment]
我取消合并单元格，再重新合并，就显示正常了。奇怪。

![[Excel 2023-12-06 16.24.41.sheet#sheet1|0-0:5-9{html}]]

嵌入的这个代码我看了下 是一模一样的。没变···是不是有缓存·····

**Comment by ljcoder2015** [comment]
我这边没有复现，应该是缓存问题
