### ISSUE TITLE
嵌入的时候，行、列的数字不符合常识

### ISSUE THREAD

**Issue by LeiYanhua** [ljcoder2015/obsidian-excel#35]
嵌入的时候，行、列的数字不符合常识.

比如，copy后嵌入第一行第1列至第二行第3列，现有格式是：

![[file-name#sheet-name|0-0:1-2]]

合乎常识的格式应当是：

![[file-name#sheet-name|1-1:2-3]]

很棒的插件。谢谢大佬！

**Comment by ljcoder2015** [comment]
都减去1就行了，之前定下来的，现在已经没法修改了，不然兼容不了以前的数据
