### ISSUE TITLE
应用或嵌入时，  |  号用  ^  号代替似乎会更好

### ISSUE THREAD

**Issue by LeiYanhua** [ljcoder2015/obsidian-excel#36]
[[file-name#sheet-name|0-0:1-2]]的格式中，如果  |  号用  ^  号代替就好了，因为在obsidian软件中， |  符号后面是别名。现有的格式导致别名功能似乎无法实现了。

**Comment by ljcoder2015** [comment]
^ 会变成块引用，现在不支持块引用
