### ISSUE TITLE
内容丢失

### ISSUE THREAD

**Issue by chaovbz** [ljcoder2015/obsidian-excel#37]
多开了几个窗口，写了一堆内容后，编辑器卡顿黑屏，重新打开后只剩下几个时前的内容，我的心在滴血。浪费了一天的时间

**Comment by chaovbz** [comment]
放大编辑器、缩小编辑器、复制内容后 内容全清空了，ctrl+z 无效。又丢了份文件，我想给你泼粪。

**Comment by ljcoder2015** [comment]
爱用不用，别在这里喷粪，老子不欠你啥
