### ISSUE TITLE
Math not working

### ISSUE THREAD

**Issue by mjdb3d** [ljcoder2015/obsidian-excel#39]
Hi, the math operators not working
<img width="88" alt="Screenshot 2024-01-07 092629" src="https://github.com/ljcoder2015/obsidian-excel/assets/6929550/d9191555-635e-4d2f-931b-e07e840954cb">

**Comment by ljcoder2015** [comment]
![sum](https://github.com/ljcoder2015/obsidian-excel/assets/15226918/21d74bd4-45fa-4378-9fc4-089be709b3d0)
it is working

**Comment by mjdb3d** [comment]
Does it support the currency cell or not?
I tried to import an Excel file that contains currency cells with math that does not work,

**Comment by ljcoder2015** [comment]
nonsupport
