### ISSUE TITLE
[FR] 让嵌入的sheet表格数据可在Obsidian中参与搜索查找

### ISSUE THREAD

**Issue by Linzeal** [ljcoder2015/obsidian-excel#4]
Markdown格式表格之所以重要，就是它可以在MD文件中直接参与数据的搜索查找。尝试了一下，嵌入的sheet表格数据无法在Obsidian中查找，但有时一些表格内容需要检索，因此两个方法看能否实现：
1. 最优方法：就是嵌入的sheet表格能在Obsidian中搜索查找。
2. 变通方法：sheet插件里提供一个功能“复制为Markdown格式表格”，这样把sheet里的表格复制后可在MD文件中粘贴为Markdown格式表格，这样能在Obsidian中搜索查找。

**Comment by ljcoder2015** [comment]
试了一下 Excalidraw 是可以直接搜索的，应该是可以实现，就是  Obsidian 文章太少了，开发起来头大

**Comment by ljcoder2015** [comment]
1.3.0 版本已实现
