### ISSUE TITLE
Unable to change date format

### ISSUE THREAD

**Issue by kevfrost** [ljcoder2015/obsidian-excel#40]
Dates are formatted mm/dd/yyyy, the standard US style.
For those of us in countries that use dd/mm/yyyy this leads to confusion.  Please can we have option to change date format to either dd/mm/yyyy or Jan 07 2024?

**Comment by ljcoder2015** [comment]
The spreadsheet does not parse the date format, it is only displayed as a string, if you are talking about the default file name, you can change it in the Settings
