### ISSUE TITLE
not possible to save properties

### ISSUE THREAD

**Issue by pachwi** [ljcoder2015/obsidian-excel#44]
Thanks for your great work - I love your plugin.

One issue:
I want to add properties.
After creating they work.

But if I make changes on the sheet all properties are gone.

![SCR-20240130-ihkc](https://github.com/ljcoder2015/obsidian-excel/assets/154025604/70ef0c43-0fb4-494e-ae80-443fd03589d7)

**Comment by ljcoder2015** [comment]
The plug-in relies on properties for data parsing. 
Data is restored to its original format when stored

**Comment by pachwi** [comment]
Thank you for your superfast answer and response!

O.K. understand - do you have an Idea - workaround to save properties? 

Example: If you have got a massive amount of Excel Tables, it would be helpful to manage this with properties - and not only by the name of the Excel sheet.

**Comment by ljcoder2015** [comment]
@pachwi 
 Perhaps you can manage this by creating a markdown file, by linking to different Excel Tables and making it an index file
