### ISSUE TITLE
Can't find the plugin on Community Plugins

### ISSUE THREAD

**Issue by Azasratruth** [ljcoder2015/obsidian-excel#49]
Has this plugin been removed from the Community Plugins list of Obsidian? cause I can't find it there to install. 

![Screenshot (788)](https://github.com/ljcoder2015/obsidian-excel/assets/66676690/1347796f-35c4-482b-a5e3-b9508a00f6e5)

**Comment by ljcoder2015** [comment]
Use excel as a keyword
