### ISSUE TITLE
[FR] 建议可设置新建表格文件的默认保存路径

### ISSUE THREAD

**Issue by Linzeal** [ljcoder2015/obsidian-excel#5]
当前的保存路径是在库的根目录，建议Excel插件提供设置，让新建表格文件可按用户的想法进行保存，比如：
- 库的根目录
- 当前文件所在目录的指定子目录
- Obsidian附件目录
- 用户指定的绝对库路径

进一步的，也可按表格文件的新建方式的不同来分别设置，比如：
- 点击ribbon栏Excel图标新建表格时
- 在当前md文件通过鼠标右键菜单或点文件菜单或Obsidian的/命令新建表格时
- 在库目录鼠标右键菜单新建表格时

**Comment by ljcoder2015** [comment]
1.3.2 版本已实现
