### ISSUE TITLE
[FR] 建议表格文件的多种新建方式

### ISSUE THREAD

**Issue by Linzeal** [ljcoder2015/obsidian-excel#6]
建议允许用户通过多种方式新建表格文件，不同的新建方式的默认保存目录不同。比如：
- 点击ribbon栏Excel图标新建表格（按Excel插件的默认保存路径保存）
- 在当前md文件通过鼠标右键菜单或点文件菜单或Obsidian的/命令新建表格（按Excel插件的默认保存路径保存）
- 在库目录鼠标右键菜单新建表格（保存在该目录）

**Comment by ljcoder2015** [comment]
1.3.2 版本已实现
