### ISSUE TITLE
[FR] 建议嵌入框的高度可自定义

### ISSUE THREAD

**Issue by Linzeal** [ljcoder2015/obsidian-excel#7]
不知道会不会上表格区域的引用。不论上不上这功能，建议嵌入框的高度可以自定义，比如定义为表格的几行，这样不论用户的表格是行数多还是少，用户可通过手动定义嵌入框的高度来刚好显示表格数据，这样不会嵌入框太高导致空行过多，或嵌入框太矮导致要经常上下拉上下滚动条。

更进一步，若能自动计算用户的非空行数，来自动计算嵌入框的高度，就更完善了。当然嵌入框的高度不能无限高，应有个默认最大值，用户可自定义此最大值。

**Comment by ljcoder2015** [comment]
1.3.2 版本已实现

**Comment by Linzeal** [comment]
建议：
1.3.3版本的设置里的默认表格高度，单位应该是像素px吧。因为本插件的嵌入体是表格，每行高度确定，建议设置里的表格高度和嵌入链接的<sheet-height>改为行数<rows>。
