### ISSUE TITLE
[FR] 建议设置一个可编辑表格的按钮

### ISSUE THREAD

**Issue by Linzeal** [ljcoder2015/obsidian-excel#8]
版本1.3之前，嵌入的表格有文件名，不论在电脑端还是手机端，点击此文件名即可编辑表格。版本1.3不显示这个文件名了，要编辑表格就需要麻烦一些，尤其在手机端。

在表格的列标和行标相交的地方为空白，建议在此处可做一个图标按钮之类的，点击即可切换编辑/只读状态。

**Comment by ljcoder2015** [comment]
1.3.1 版本已实现
