### ISSUE TITLE
[FR] 从微软Excel中导入数据时能否做数据链接以便后续数据有更新时直接做数据刷新

### ISSUE THREAD

**Issue by Linzeal** [ljcoder2015/obsidian-excel#9]
一个想法，看能不能上这样的功能：

目前微软Excel的xlsx文件无法在Obsidian中预览，obsidian-excel插件可导入xlsx文件，能否在导入时仅导入指定的部分数据，并做数据链接。后续微软Excel的xlsx文件有更新时，在obsidian-excel插件中刷新下数据就行，就如微软Excel中的数据刷新一样，而不是重复做导入。

**Comment by ljcoder2015** [comment]
这个没法实现，导入只是把 excel 的数据解析出来，转换成 obsidain-excel 的数据，跟源文件没啥关系
